########################################################
##### Makefile                     written by Kenji KISE

SRC = queens.c
TRG = qn24b_base

########################################################
$(TRG): $(SRC)
	gcc -Wall -static -O2 $(SRC) -o $(TRG)

clean :
	rm -f *.il *~ core *.o *.s $(TRG)

all:
	$(MAKE) $(TRG)
##### End of Makefile ##################################
